package br.com.avaliacao2_arthurguirao.view;

import br.com.avaliacao2_arthurguirao.ctr.RelatorioCTR;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import br.com.avaliacao2_arthurguirao.dto.BibliotecarioDTO;
import java.awt.Toolkit; 
import java.util.Map;
import java.util.HashMap;

public class PrincipalView extends javax.swing.JFrame {
        
    Map parametros = new HashMap();
    
    public PrincipalView(BibliotecarioDTO bibliotecarioDTO) {
        initComponents();
        this.setLocationRelativeTo(null);
        if(bibliotecarioDTO.getTipo_bib().equalsIgnoreCase("COMUM")){
           itemMenuBibliotecario.setVisible(false);
           itemMenuLivro.setVisible(false);
           itemMenuFornecedor.setVisible(false);
           itemMenuEmprestimo.setVisible(false);
           itemMenuRelatorioLivros.setVisible(false);
        }
    }
    private void abreLivroVIEW(){
        LivroVIEW livroVIEW = new LivroVIEW();
        this.desktopPane.add(livroVIEW);
        livroVIEW.setVisible(true);
        livroVIEW.setPosicao();
    }
    
    private void abreEmprestimoVIEW(){
        EmprestimoVIEW emprestimoVIEW = new EmprestimoVIEW();
        this.desktopPane.add(emprestimoVIEW);
        emprestimoVIEW.setVisible(true);
        emprestimoVIEW.setPosicao();
    }
    
    private void abreBibliotecarioVIEW(){
        BibliotecarioVIEW bibliotecarioVIEW = new BibliotecarioVIEW();
        this.desktopPane.add(bibliotecarioVIEW);
        bibliotecarioVIEW.setVisible(true);
        bibliotecarioVIEW.setPosicao();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageicon = new ImageIcon(getClass().getResource("imagens/tela_inicial.jpg"));
        Image image = imageicon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics graphics){
                graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        menuBar = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemMenuFornecedor = new javax.swing.JMenuItem();
        itemMenuLivro = new javax.swing.JMenuItem();
        itemMenuAluno = new javax.swing.JMenuItem();
        itemMenuBibliotecario = new javax.swing.JMenuItem();
        menuEmprestimo = new javax.swing.JMenu();
        itemMenuEmprestimo = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        itemMenuRelatorioLivros = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setMnemonic('f');
        menuCadastro.setText("Cadastrar");

        itemMenuFornecedor.setMnemonic('o');
        itemMenuFornecedor.setText("Fornecedor");
        itemMenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFornecedorActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuFornecedor);

        itemMenuLivro.setMnemonic('x');
        itemMenuLivro.setText("Livro");
        itemMenuLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuLivroActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuLivro);

        itemMenuAluno.setText("Aluno");
        itemMenuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAlunoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuAluno);

        itemMenuBibliotecario.setText("Bibliotecário");
        itemMenuBibliotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuBibliotecarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuBibliotecario);

        menuBar.add(menuCadastro);

        menuEmprestimo.setText("Empréstimo");

        itemMenuEmprestimo.setText("Realizar Empréstimo");
        itemMenuEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEmprestimoActionPerformed(evt);
            }
        });
        menuEmprestimo.add(itemMenuEmprestimo);

        menuBar.add(menuEmprestimo);

        menuRelatorios.setText("Relatórios");

        itemMenuRelatorioLivros.setText("Relatório dos livros");
        itemMenuRelatorioLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioLivrosActionPerformed(evt);
            }
        });
        menuRelatorios.add(itemMenuRelatorioLivros);

        menuBar.add(menuRelatorios);

        menuSair.setMnemonic('h');
        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuBar.add(menuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1233, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuLivroActionPerformed
        abreLivroVIEW();
    }//GEN-LAST:event_itemMenuLivroActionPerformed

    private void itemMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFornecedorActionPerformed
        abreFornecedorVIEW();
    }//GEN-LAST:event_itemMenuFornecedorActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        sair();// TODO add your handling code here:
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        sair();        // TODO add your handling code here:
    }//GEN-LAST:event_menuSairMouseClicked

    private void itemMenuEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEmprestimoActionPerformed
        abreEmprestimoVIEW();
    }//GEN-LAST:event_itemMenuEmprestimoActionPerformed

    private void itemMenuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAlunoActionPerformed
        abreAlunoVIEW();
    }//GEN-LAST:event_itemMenuAlunoActionPerformed

    private void itemMenuBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuBibliotecarioActionPerformed
        abreBibliotecarioVIEW();
    }//GEN-LAST:event_itemMenuBibliotecarioActionPerformed

    private void itemMenuRelatorioLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioLivrosActionPerformed
        RelatorioCTR relatorioCTR = new RelatorioCTR();
        relatorioCTR.abrirRelatorio("Rel_produto_geral.jasper", "Relatório de livros", parametros).setVisible(true);
    }//GEN-LAST:event_itemMenuRelatorioLivrosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrincipalView().setVisible(true);
//            }
//        });
//    }
    
    private void sair(){
        Object[] options = {"Sair", "Cancelar"};
        if(JOptionPane.showOptionDialog(null, "Deseja sair do sistema?", "informação",
                JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0){
            System.exit(0);
        }
    }
    
    private void abreFornecedorVIEW(){
        FornecedorVIEW fornecedorVIEW = new FornecedorVIEW();
        this.desktopPane.add(fornecedorVIEW);
        fornecedorVIEW.setVisible(true);
        fornecedorVIEW.setPosicao();
    } 
    
    private void abreAlunoVIEW(){
        AlunoVIEW alunoVIEW = new AlunoVIEW();
        this.desktopPane.add(alunoVIEW);
        alunoVIEW.setVisible(true);
        alunoVIEW.setPosicao();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemMenuAluno;
    private javax.swing.JMenuItem itemMenuBibliotecario;
    private javax.swing.JMenuItem itemMenuEmprestimo;
    private javax.swing.JMenuItem itemMenuFornecedor;
    private javax.swing.JMenuItem itemMenuLivro;
    private javax.swing.JMenuItem itemMenuRelatorioLivros;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuEmprestimo;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables

}
